### ISSUE TITLE
Auto-start dcd-serer?

### ISSUE THREAD

**Issue by miguelmartin75** [idanarye/vim-dutyl#20]
Why doens't this plugin automatically start dcd-server if it's not running? Unless it does, however it does not for me.

**Comment by idanarye** [comment]
Unless I change the VimProc requirement from _optional_ to _mandatory_, I can't run `dcd-server` as a subprocess. This means that I won't be able to automatically close it once the user closes Vim. I don't want to spawn such daemon behind the user's back - as long as I don't completely control the process from the plugin I believe the user should be the one to decide when to start/stop it.

I do, however, provide helpers - the `:DUDCDstartServer`, `:DUDCDstopServer` and `:DUDCDrestartServer` can be used to easily control `dcd-server` from Vim. So even if I don't start it automatically for you, you can easily start it yourself.

**Comment by miguelmartin75** [comment]
Ah okay, thanks.
