### ISSUE TITLE
Dutyl + neocomplete

### ISSUE THREAD

**Issue by whitebyte** [idanarye/vim-dutyl#21]
Hi,
I'm trying to make syntax complete popup automatic (without C-x C-O). I'm using [neocomplete.vim](https://github.com/Shougo/neocomplete.vim). Tried to add `autocmd FileType d setlocal omnifunc=dutyl#dComplete` to my vimrc but still no luck, quick look at the docs didn't brought enlightening. Could you please point me to the right direction?

**Comment by idanarye** [comment]
I never used neocomplete, but a quick google shows that someone opened a ticket on this issue there(https://github.com/Shougo/neocomplete.vim/issues/340) and Shougo answered, so you might want to look there.

**Comment by idanarye** [comment]
It looks like the asker of that question wrote a blog post about configuring Dutyl and it has a section  about configuring it with neocomplete: http://prog3.com/sbdm/blog/Ice_Nature/article/details/40225205#t5

**Comment by whitebyte** [comment]
I had to find it by myself. Thank you for the help and sorry for the LMGTFY-style ticket.
