### ISSUE TITLE
no completion after e.g. io when importing module as import io = std.stdio;

### ISSUE THREAD

**Issue by kraxli** [idanarye/vim-dutyl#22]
Hi 
how can I get auto-completion after "io." when I import a module as e.g. 

```dlang
import io = std.stdio;
```

Is this not supported yet?

Thanks David

**Comment by Hackerpilot** [comment]
This is a DCD problem. Please file it here: https://github.com/Hackerpilot/DCD/issues

**Comment by kraxli** [comment]
thanks for redirecting me to the right source of issue.
