### ISSUE TITLE
Ability to use dcd-client --tcp?

### ISSUE THREAD

**Issue by fsouza** [idanarye/vim-dutyl#35]
Reading the history of issues and the repository history, it was possible to register tools with an array (i.e. ``call duty#register#tool('dcd-client', ['dcd-client', '--tcp'])``), but this no longer works.

Would you be interested in having this feature back? If so, I can try to prepare a patch.

**Comment by idanarye** [comment]
I just check and it works - but you have to use `--tcp` when you start the DCD server as well. If you are starting it via Dutyl's `:DUDCDstartServer` you need:

```vim
call duty#register#tool('dcd-client', ['dcd-client', '--tcp'])
call duty#register#tool('dcd-server', ['dcd-server', '--tcp'])
```

**Comment by fsouza** [comment]
Hm, when I try this, I get the following error during completion:

```
Error detected while processing function dutyl#dComplete:
line   35:
Unable to complete: Vim(return):E730: using List as a String
Press ENTER or type command to continue
```

I'm running on neovim, that might be the issue. I'll test with regular vim later. Thanks!

**Comment by idanarye** [comment]
OK, I see now. This feature is in `develop`, but not yet in `master`. I'll create a release now.

**Comment by fsouza** [comment]
@idanarye oh, nice to know! I can use `develop` if you prefer to not cut a release now :)

**Comment by fsouza** [comment]
Ah, you already did. Thanks! :D :D

**Comment by fsouza** [comment]
It worked, thank you very much! :)
