### ISSUE TITLE
Subpar plugin performance on Windows

### ISSUE THREAD

**Issue by tastyminerals** [idanarye/vim-dutyl#43]
I have compiled and installed DCD, added **vim-dutyl** via pathogen. Set `let g:dutyl_stdImportPaths=['C:\D\dmd2\windows\bin']`. Tried `:DUDCDstartServer`, it starts the server correctly. However, when I hit `<Tab>` not only do I have to wait for a sec or two but the completion is off and makes no sense at all. In the server logs I see that it cannot find the location of the modules which is probably the reason for such behaviour. 
![Capture](https://user-images.githubusercontent.com/7676160/71383796-e2b50f80-25d5-11ea-81ad-1f51dac0afb6.PNG)

I have feeling it simply does not work and vim uses completion from `vimcompletesme` plugin which is triggered with `<Tab>` too. Do I need to remap it then? Finally, what do I need to do to make it work correctly?

Also, `let g:dutyl_dontUseVimProc=1` does not seem to work because cmd window pops up anyway.

**Comment by idanarye** [comment]
Are you sure `C:\D\dmd2\windows\bin` is the right path? I don't have a handy Windows machine right now, but shouldn't `bin` be where the binaries are installed?

The directory you should be pointing `g:dutyl_stdImportPaths` at should contain the following files:
* `core`
* `etc`
* `index.d`
* `object.d`
* `std`
* `unittest.d`

I should probably be under `C:\D\dmd2` somewhere - I don't really know where...

As for `let g:dutyl_dontUseVimProc=1` - that's exactly it's function. If you are not using VimProc you'll get that CMD window.

**Comment by tastyminerals** [comment]
Yes, you are right. The bin folder on Windows contains only precompiled binaries but not phobos sources. Closing.
