### ISSUE TITLE
Integrate with Vundle

### ISSUE THREAD

**Issue by carun** [idanarye/vim-dutyl#44]
It would be good to have this integrated with [Vundle](https://github.com/VundleVim/Vundle.vim) to ease the installation.

**Comment by idanarye** [comment]
What's there to integrate? You just put `Plugin 'idanarye/vim-dutyl'` like you would with any other plugin.

**Comment by carun** [comment]
Right, that works. The doc probably needs to mention it.

**Comment by idanarye** [comment]
Vundle's README explains how to do it. There is no need for every Vim plugin to explain how you install it with every plugin manager.
